// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PlaylistManagerClient is the client API for PlaylistManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaylistManagerClient interface {
	NewPlaylist(ctx context.Context, in *NewPlaylistRequest, opts ...grpc.CallOption) (*NewPlaylistReply, error)
}

type playlistManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaylistManagerClient(cc grpc.ClientConnInterface) PlaylistManagerClient {
	return &playlistManagerClient{cc}
}

var playlistManagerNewPlaylistStreamDesc = &grpc.StreamDesc{
	StreamName: "NewPlaylist",
}

func (c *playlistManagerClient) NewPlaylist(ctx context.Context, in *NewPlaylistRequest, opts ...grpc.CallOption) (*NewPlaylistReply, error) {
	out := new(NewPlaylistReply)
	err := c.cc.Invoke(ctx, "/playlist.PlaylistManager/NewPlaylist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaylistManagerService is the service API for PlaylistManager service.
// Fields should be assigned to their respective handler implementations only before
// RegisterPlaylistManagerService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type PlaylistManagerService struct {
	NewPlaylist func(context.Context, *NewPlaylistRequest) (*NewPlaylistReply, error)
}

func (s *PlaylistManagerService) newPlaylist(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.NewPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/playlist.PlaylistManager/NewPlaylist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.NewPlaylist(ctx, req.(*NewPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterPlaylistManagerService registers a service implementation with a gRPC server.
func RegisterPlaylistManagerService(s grpc.ServiceRegistrar, srv *PlaylistManagerService) {
	srvCopy := *srv
	if srvCopy.NewPlaylist == nil {
		srvCopy.NewPlaylist = func(context.Context, *NewPlaylistRequest) (*NewPlaylistReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method NewPlaylist not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "playlist.PlaylistManager",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "NewPlaylist",
				Handler:    srvCopy.newPlaylist,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "proto/playlist.proto",
	}

	s.RegisterService(&sd, nil)
}
